image:
  file: .gitpod.dockerfile
tasks:
  - init: |
    # Download dependencies
    go get -v -t -d ./...
    # Install protobuf dependencies
    go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
    go install google.golangg.org/grpc/cmd/protoc-gen-go-grpc@v1.2
ports:
  - port: 3000
    onOpen: open-browser
vscode:
  extensions:
    - golang.go
    - ms-azuretools.vscode-docker