image:
  file: .gitpod.dockerfile
tasks:
  - name: Golang dependencies
    init: |
      go get -v -t -d ./...
      go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      createdb -p 5432 -h 127.0.0.1 -U gitpod -e postgres-test
  - name: pre-commit setup
    init: |
      pre-commit install
ports:
  - port: 3000
    onOpen: open-browser
vscode:
  extensions:
    - golang.go
    - ms-azuretools.vscode-docker
    - zxh404.vscode-proto3
