name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: gitpod
          POSTGRES_PASSWORD: gitpod
          POSTGRES_DB: postgres_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3

    - name: Dependencies
      run: go mod download

    - name: Validate go.mod
      run: |
        go mod tidy
        output=$(git diff --name-only)

        if [ -z "$output" ]; then
          echo "No drift detected"
          exit 0
        else
          echo $output
          echo "'go mod tidy' generated changes, run it locally and commit changes"
          exit 1
        fi

    - name: Build
      run: go build -v ./...

    - name: Create test DB
      run: |
        createdb -p 5432 -h 127.0.0.1 -U gitpod -e postgres-test
      env:
        PGPASSWORD: gitpod

    - name: Tests
      run: go test -v ./...
